feat: add support for m3u playlist files and make it the default mode

diff --git a/termv b/termv
--- a/termv
+++ b/termv
@@ -5,9 +5,11 @@ BASH_BINARY="$(which bash)"
 TERMV_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/termv"
 TERMV_AUTO_UPDATE=${TERMV_AUTO_UPDATE:-true}
 TERMV_FULL_SCREEN=${TERMV_FULL_SCREEN:-false}
+TERMV_LEGACY_FORMAT=${TERMV_LEGACY_FORMAT:-false}
 
 TERMV_CHANNELS_URL=${TERMV_CHANNELS_URL:-"https://iptv-org.github.io/api/channels.json"}
 TERMV_STREAMS_URL=${TERMV_STREAMS_URL:-"https://iptv-org.github.io/api/streams.json"}
+TERMV_PLAYLISTS_URL=${TERMV_PLAYLISTS_URL:-"https://iptv-org.github.io/iptv/index.m3u"}
 
 FZF_VERSION=$(fzf --version | cut -d '.' -f 2- | cut -d ' ' -f 1 )
 
@@ -48,6 +50,7 @@ usage() {
     _phi "-h, --help                Print this help text and exit."
     _phi "-v, --version             Print program version and exit."
     _phi "-u, --update              Update channel list to latest version."
+    _phi "-l, --legacy              Use legacy sources format (JSON)."
     _pht
     _pht "  Player Options:"
     _phi "-f, --full-screen         Open mpv in fullscreen."
@@ -58,12 +61,22 @@ usage() {
     _phi "TERMV_SWALLOW             Always swallow terminal during playback. (default: false)"
     _phi "TERMV_FULL_SCREEN         Always open mpv in fullscreen. (default: false)"
     _phi "TERMV_DEFAULT_MPV_FLAGS   Default arguments which are passed to mpv. (default: --no-resume-playback)"
-    _phi "TERMV_CHANNELS_URL             URL to the channel list. (default: https://iptv-org.github.io/api/channels.json)"
+    _phi "TERMV_CHANNELS_URL            URL to the channel list. (default: https://iptv-org.github.io/api/channels.json)"
     _phi "                          Any other URL must be in the same format as the default one."
     _phi "TERMV_STREAMS_URL             URL to the streams list. (default: https://iptv-org.github.io/api/streams.json)"
     _phi "                          Any other URL must be in the same format as the default one."
+    _phi "TERMV_PLAYLISTS_URL           URL to the playlists file. (default: https://iptv-org.github.io/iptv/index.m3u)"
+    _phi "                          Any other URL must be in the same format as the default one."
     _pht "  Improve me on GitHub:"
     _phi "https://github.com/Roshan-R/termv"
+}
+
+update_files() {
+    if [ "${TERMV_LEGACY_FORMAT}" = true ]; then
+        update_jsonfiles
+    else
+        update_m3ufiles
+    fi
 }
 
 merge_json_files() {
@@ -75,14 +88,13 @@ merge_json_files() {
     rm "${TERMV_CACHE_DIR:?}/tmp_channels_data.json"
 }
 
-update_jsonfiles(){
+update_jsonfiles() {
     update_channelsfile
     update_streamsfiles
     merge_json_files
 }
 
 update_channelsfile() {
-
     channelsEtagpath="${TERMV_CACHE_DIR:?}/channels_etag"
     printf '%s' "Downloading ${TERMV_CHANNELS_URL:?}... "
     [ -f "${channelsEtagpath:?}" ] && oldChannelsetag=$(<"${channelsEtagpath}") || oldChannelsetag="null"
@@ -96,7 +108,7 @@ update_channelsfile() {
         touch "${TERMV_CACHE_DIR:?}/channels_data.json" ;
         printf '\033[33;1m %s \033[0m\n' "Your version is already up to date." ;
     elif [ ${channelsDownloaded} -eq 1 ]; then
-      mv -f "${TERMV_CACHE_DIR:?}/channels_data.json_new" "${TERMV_CACHE_DIR:?}/channels_data.json"
+        mv -f "${TERMV_CACHE_DIR:?}/channels_data.json_new" "${TERMV_CACHE_DIR:?}/channels_data.json"
         printf '\033[32;1m %s \033[0m\n' "Done!" ;
     elif [ ${channelsDownloaded} -eq 0 ]; then
         rm -f "${channelsEtagpath:?}" "${TERMV_CACHE_DIR:?}/channels_data.json_new"
@@ -107,7 +119,6 @@ update_channelsfile() {
 }
 
 update_streamsfiles() {
-
     streamsEtagpath="${TERMV_CACHE_DIR:?}/streams_etag"
     printf '%s' "Downloading ${TERMV_STREAMS_URL:?}... "
     [ -f "${streamsEtagpath:?}" ] && oldStreamsetag=$(<"${streamsEtagpath}") || oldStreamsetag="null"
@@ -121,7 +132,7 @@ update_streamsfiles() {
         touch "${TERMV_CACHE_DIR:?}/streams_data.json" ;
         printf '\033[33;1m %s \033[0m\n' "Your version is already up to date." ;
     elif [ ${streamsDownloaded} -eq 1 ]; then
-      mv -f "${TERMV_CACHE_DIR:?}/streams_data.json_new" "${TERMV_CACHE_DIR:?}/streams_data.json"
+        mv -f "${TERMV_CACHE_DIR:?}/streams_data.json_new" "${TERMV_CACHE_DIR:?}/streams_data.json"
         printf '\033[32;1m %s \033[0m\n' "Done!" ;
     elif [ ${streamsDownloaded} -eq 0 ]; then
         rm -f "${streamsEtagpath:?}" "${TERMV_CACHE_DIR:?}/streams_data.json_new"
@@ -129,14 +140,66 @@ update_streamsfiles() {
         printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
         exit 1
     fi
+}
 
+convert_m3u_files() {
+    echo "[" > temp.json
+    while IFS= read -r line; do
+        if [[ "$line" =~ tvg-name=\"([^\"]+)\" || "$line" =~ tvg-id=\"([^\"]+)\" ]]; then
+            id="${BASH_REMATCH[1]}"
+        elif [[ "$line" == \#EXTINF* ]]; then
+            id="$(echo $line | cut -d ',' -f2 | sed 's/\r$//')"
+        elif [[ "$line" == http* ]]; then
+            if [ ! -z "$id" ]; then
+                url="$(echo $line | sed 's/\r$//')"
+                echo "{\"id\":\"$id\",\"name\":\"$id\"," >> temp.json
+                echo "\"url\":\"$url\"," >> temp.json
+                echo "\"categories\":[\"general\"],\"is_nsfw\":false," >> temp.json
+                echo "\"languages\":\"por\",\"country\":\"PT\"}," >> temp.json
+            fi
+            id=""
+        fi
+    done < "${TERMV_CACHE_DIR:?}/playlists_data.m3u"
+    truncate -s-2 temp.json
+    echo "]" >> temp.json
+    jq . temp.json > "${TERMV_CACHE_DIR:?}/data.json"
+    rm temp.json
+}
+
+update_m3ufiles() {
+    update_playlistsfiles
+    convert_m3u_files
+}
+
+update_playlistsfiles() {
+    playlistsEtagpath="${TERMV_CACHE_DIR:?}/playlists_etag"
+    printf '%s' "Downloading ${TERMV_PLAYLISTS_URL:?}... "
+    [ -f "${playlistsEtagpath:?}" ] && oldPlaylistsetag=$(<"${playlistsEtagpath}") || oldPlaylistsetag="null"
+
+    curl -s "${TERMV_PLAYLISTS_URL}" --etag-compare "${playlistsEtagpath:?}" --etag-save "${playlistsEtagpath:?}" -o "${TERMV_CACHE_DIR:?}/playlists_data.m3u_new" \
+    -H "accept-encoding:gzip" --compressed && playlistsDownloaded=1 || playlistsDownloaded=0
+
+    newPlaylistsetag=$(<"${playlistsEtagpath}")
+
+    if [ ${playlistsDownloaded} -eq 1 ] && [ "${newPlaylistsetag}" = "${oldPlaylistsetag}" ]; then
+        touch "${TERMV_CACHE_DIR:?}/playlists_data.m3u" ;
+        printf '\033[33;1m %s \033[0m\n' "Your version is already up to date." ;
+    elif [ ${playlistsDownloaded} -eq 1 ]; then
+        mv -f "${TERMV_CACHE_DIR:?}/playlists_data.m3u_new" "${TERMV_CACHE_DIR:?}/playlists_data.m3u"
+        printf '\033[32;1m %s \033[0m\n' "Done!" ;
+    elif [ ${playlistsDownloaded} -eq 0 ]; then
+        rm -f "${playlistsEtagpath:?}" "${TERMV_CACHE_DIR:?}/playlists_data.m3u_new"
+        echo "${oldPlaylistsetag}" > "${playlistsEtagpath}"
+        printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
+        exit 1
+    fi
 }
 
 # check if necessary programs are installed
 DEPENDENCIES="fzf jq curl gawk"
 [ "$(uname -o)" != "Android" ] && DEPENDENCIES="mpv ${DEPENDENCIES}"
 for prog in ${DEPENDENCIES}; do
-     ! has "$prog" && dependencies_not_installed="${dependencies_not_installed}${prog}, "
+    ! has "$prog" && dependencies_not_installed="${dependencies_not_installed}${prog}, "
 done
 
 [ -n "${dependencies_not_installed}" ] && _pemx "Missing dependencies, please install: ${dependencies_not_installed%??}."
@@ -148,7 +211,9 @@ while [ "$1" ]; do
         "-v"|"--version")
             version ; exit 0 ;;
         "-u"|"--update")
-            update_jsonfiles ; exit ;;
+            update_files; exit ;;
+        "-l"|"--legacy")
+            TERMV_LEGACY_FORMAT=true ; shift ;;
         "-f"|"--full-screen")
             TERMV_FULL_SCREEN=true   ; shift ;;
         "-s"|"--swallow")
@@ -171,21 +236,24 @@ done
 [[ -n "${TERMV_LANGUAGE}" ]] && echo "Chosen language: $TERMV_LANGUAGE" && TERMV_FILTER="$TERMV_FILTER | select(.languages[0].name == \"$TERMV_LANGUAGE\")"
 [[ -n "${TERMV_COUNTRY}" ]] && echo "Chosen country: $TERMV_COUNTRY" && TERMV_FILTER="$TERMV_FILTER | select(.countries[0].name == \"$TERMV_COUNTRY\")"
 
-[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/channels_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles ; }
-[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/streams_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles ; }
+if [ "${TERMV_LEGACY_FORMAT}" = true ]; then
+    [ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/channels_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles ; }
+    [ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/streams_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles ; }
+else
+    [ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/playlists_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_m3ufiles ; }
+fi
 
-
-CHANNELS_LIST=$(jq -r ".[] $TERMV_FILTER | \"\(.name) \t \(.categories[]? // \"N/A\") \t \(.languages[]? // \"N/A\") \t \(.country? // \"N/A\") \t \(.url)\"" "${TERMV_CACHE_DIR:?}/data.json" |\
-                gawk -v max="${COLUMNS:-80}" 'BEGIN { RS="\n"; FS=" \t " }
-                    {
-                      name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
-                      category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
-                      languages = substr(gensub(/\s+> (.*)/, "\\1", "g", $3),0,max/8)
-                      countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
-                      channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
-                      print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
-                    }' | column -t -s $'\t' \
-                )
+CHANNELS_LIST=$(jq -r ".[] $TERMV_FILTER | \"\(.name) \t \(.categories[]? // \"N/A\") \t \(.languages[]? // \"N/A\") \t \(.country? // \"N/A\") \t \(.url)\"" "${TERMV_CACHE_DIR:?}/data.json" | \
+    gawk -v max="${COLUMNS:-80}" 'BEGIN { RS="\n"; FS=" \t " }
+        {
+            name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
+            category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
+            languages = substr(gensub(/\s+> (.*)/, "\\1", "g", $3),0,max/8)
+            countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
+            channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
+            print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
+        }' | column -t -s $'\t' \
+    )
 
 _play() {
     printf '%s\n' "Fetching channel, please wait..."
@@ -204,25 +272,25 @@ _play() {
 }
 
 _playbg() {
-    { setsid -f mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate >/dev/null 2>&1 ; }
+    { setsid -f mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate >/dev/null 2>&1; }
 }
 
 export -f _play
 export -f _playbg
 
-if [ $(echo "$FZF_VERSION < 25.0" | bc) == 1 ];then
-SHELL="${BASH_BINARY}" \
-            fzf -e -i --reverse --cycle --with-nth="1..-2"\
-                --bind "enter:execute(_play {})"\
-                --bind "double-click:execute(_play {})"\
-                --header="Select channel (press Escape to exit)" -q "${*:-}" \
-            < <( printf '%s\n' "${CHANNELS_LIST}" )
+if [ $(echo "$FZF_VERSION < 25.0" | bc) == 1 ]; then
+    SHELL="${BASH_BINARY}" \
+        fzf -e -i --reverse --cycle --with-nth="1..-2"\
+            --bind "enter:execute(_play {})"\
+            --bind "double-click:execute(_play {})"\
+            --header="Select channel (press Escape to exit)" -q "${*:-}" \
+        < <( printf '%s\n' "${CHANNELS_LIST}" )
 else
-SHELL="${BASH_BINARY}" \
-            fzf -e -i --reverse --cycle --with-nth="1..-2"\
-                --bind "alt-]:execute-silent(_playbg {})"\
-                --bind "enter:execute(_play {})"\
-                --bind "double-click:execute(_play {})"\
-                --header="Select channel (press Escape to exit)" -q "${*:-}" \
-            < <( printf '%s\n' "${CHANNELS_LIST}" )
+    SHELL="${BASH_BINARY}" \
+        fzf -e -i --reverse --cycle --with-nth="1..-2"\
+            --bind "alt-]:execute-silent(_playbg {})"\
+            --bind "enter:execute(_play {})"\
+            --bind "double-click:execute(_play {})"\
+            --header="Select channel (press Escape to exit)" -q "${*:-}" \
+        < <( printf '%s\n' "${CHANNELS_LIST}" )
 fi
